[package]
name = "logos-storage-service"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[[bin]]
name = "logos-storage-service"
path = "src/main.rs"
test = false
bench = false

[lib]
path = "src/lib.rs"

[features]
block-probe = []

[dependencies]
logos-abi = { path = "../logos-abi" }
logos-service-rt = { path = "../logos-service-rt" }
logos-store = { path = "../logos-store" }
