[package]
name = "logos-storage-service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "logos-storage-service"
path = "src/main.rs"
test = false
bench = false

[dependencies]
logos-core = { path = "../logos-core" }
logos-service-rt = { path = "../logos-service-rt" }
logos-store = { path = "../logos-store" }
