[workspace]
members = ["crates/logos-abi", "crates/logos-core", "crates/logos-terminal", "crates/logos-terminal-service", "crates/logos-sessions-service", "crates/logos-test"]
default-members = ["crates/logos-abi", "crates/logos-core", "crates/logos-terminal", "crates/logos-test"]
resolver = "3"

[package]
name = "logos-uefi"
version = "0.1.0"
edition = "2024"

[dependencies]
logos-core = { path = "crates/logos-core" }
logos-abi = { path = "crates/logos-abi" }
logos-terminal = { path = "crates/logos-terminal" }
uefi = { version = "0.35", features = ["panic_handler"] }

[features]
test-hooks = []
