use super::{Fixture, Runner, Scenario};

pub(crate) const SCENARIOS: &[Scenario] = &[
    configured("core/boot-normal", "core", &[], Fixture::Fresh),
    configured("platform/missing-sessions", "platform", &[], Fixture::MissingSessions),
    configured("platform/missing-terminal", "platform", &[], Fixture::MissingTerminal),
    configured("platform/incompatible-sessions", "platform", &[], Fixture::IncompatibleSessions),
    configured("platform/missing-store", "platform", &[], Fixture::MissingStore),
    configured("platform/missing-network", "platform", &[], Fixture::MissingNetwork),
    scenario("core/boot-recovery", "core", Fixture::Fresh),
    scenario("core/ipc-request-reply", "core", Fixture::Fresh),
    scenario("core/ipc-cancellation", "core", Fixture::Fresh),
    scenario("core/task-block-wake", "core", Fixture::Fresh),
    scenario("core/capability-denied", "core", Fixture::Fresh),
    scenario("core/capability-revoked", "core", Fixture::Fresh),
    scenario("core/driver-reset-recovery", "core", Fixture::Fresh),
    scenario("core/resource-reclamation", "core", Fixture::Fresh),
    scenario("core/panic-diagnostics", "core", Fixture::Fresh),
    configured(
        "console/input-qwerty",
        "console",
        &["layout qwerty", "assert-input"],
        Fixture::Shared,
    ),
    configured(
        "console/input-azerty",
        "console",
        &["layout azerty", "assert-input"],
        Fixture::Shared,
    ),
    scenario("console/editing-utf8", "console", Fixture::Shared),
    scenario("console/history", "console", Fixture::Shared),
    configured(
        "console/structured-command",
        "console",
        &["assert-tasks", "assert-sessions"],
        Fixture::Shared,
    ),
    configured("console/capability-denied", "console", &["deny-recovery"], Fixture::Shared),
    configured("console/input-capability-denied", "console", &["deny-layout"], Fixture::Shared),
    configured("console/display-capability-denied", "console", &["deny-display"], Fixture::Shared),
    configured("console/session-capability-denied", "console", &["deny-session"], Fixture::Shared),
    configured("console/cancellation", "console", &["assert-cancel"], Fixture::Shared),
    configured(
        "console/display-restart",
        "console",
        &["assert-display", "assert-terminal-service-restart"],
        Fixture::Shared,
    ),
    configured("console/input-service-restart", "console", &["assert-restart"], Fixture::Shared),
    configured(
        "console/terminal-service-restart",
        "console",
        &["assert-terminal-service-restart"],
        Fixture::Shared,
    ),
    configured(
        "console/sessions-service-restart",
        "console",
        &["assert-sessions-service-restart"],
        Fixture::Shared,
    ),
    configured(
        "persistence/storage-service-restart",
        "persistence",
        &["assert-storage-service-restart"],
        Fixture::Shared,
    ),
    configured(
        "platform/terminal-panic-containment",
        "platform",
        &["assert-terminal-service-panic"],
        Fixture::Fresh,
    ),
    configured(
        "platform/terminal-fault-containment",
        "platform",
        &["assert-terminal-service-fault"],
        Fixture::Fresh,
    ),
    configured(
        "platform/sessions-panic-containment",
        "platform",
        &["assert-sessions-service-panic"],
        Fixture::Fresh,
    ),
    configured(
        "platform/sessions-fault-containment",
        "platform",
        &["assert-sessions-service-fault"],
        Fixture::Fresh,
    ),
    configured(
        "platform/store-panic-containment",
        "platform",
        &["assert-storage-service-panic"],
        Fixture::Fresh,
    ),
    configured(
        "platform/store-fault-containment",
        "platform",
        &["assert-storage-service-fault"],
        Fixture::Fresh,
    ),
    configured(
        "platform/network-panic-containment",
        "platform",
        &["assert-network-service-panic"],
        Fixture::Fresh,
    ),
    configured(
        "platform/network-fault-containment",
        "platform",
        &["assert-network-service-fault"],
        Fixture::Fresh,
    ),
    configured_with_runner(
        "persistence/block-read-flush",
        "persistence",
        &[],
        Fixture::Persistence,
        Runner::PersistenceFixture,
    ),
    configured_with_runner(
        "persistence/terminal-history",
        "persistence",
        &["layout azerty", "layout qwerty", "persistence/terminal-history"],
        Fixture::Persistence,
        Runner::PersistenceTerminalHistory,
    ),
    configured_with_runner(
        "persistence/block-timeout-reset",
        "persistence",
        &[],
        Fixture::Persistence,
        Runner::PersistenceTimeoutReset,
    ),
    configured_with_runner(
        "persistence/capability-denied",
        "persistence",
        &["persistence/capability-denied"],
        Fixture::Persistence,
        Runner::PersistenceCapabilityDenied,
    ),
    scenario("console/recovery-handoff", "console", Fixture::Fresh),
    scenario("platform/manifest-valid", "platform", Fixture::Fresh),
    scenario("platform/manifest-invalid", "platform", Fixture::Fresh),
    scenario("platform/dependency-order", "platform", Fixture::Shared),
    scenario("platform/dependency-cycle-rejected", "platform", Fixture::Shared),
    scenario("platform/startup-failure", "platform", Fixture::Fresh),
    configured(
        "platform/runtime-crash-restart",
        "platform",
        &["assert-crash-restart"],
        Fixture::Shared,
    ),
    scenario("platform/dependency-loss", "platform", Fixture::Shared),
    configured(
        "platform/restart-backoff",
        "platform",
        &["assert-restart-backoff"],
        Fixture::Shared,
    ),
    scenario("platform/resource-reclamation", "platform", Fixture::Shared),
    scenario("platform/protocol-compatible", "platform", Fixture::Shared),
    scenario("platform/protocol-incompatible", "platform", Fixture::Shared),
    scenario("platform/unauthorized-capability", "platform", Fixture::Shared),
    scenario("platform/diagnostics", "platform", Fixture::Shared),
    scenario("platform/native-payload-staged", "platform", Fixture::Fresh),
    scenario("platform/service-address-space", "platform", Fixture::Fresh),
    scenario("platform/native-image-mapped", "platform", Fixture::Fresh),
    scenario("platform/service-privilege-setup", "platform", Fixture::Fresh),
    scenario("platform/service-ring3-transition", "platform", Fixture::Fresh),
    configured(
        "platform/native-service-ready",
        "platform",
        &[
            "health",
            "assert-ping",
            "tasks",
            "assert-services",
            "assert-drivers",
            "trace",
            "assert-inspect",
            "restart virtio-balloon",
            "cancel virtio-balloon",
            "layout azerty",
            "layout qwerty",
            "echo hello",
            "help clear",
            "commands",
            "clear",
        ],
        Fixture::Shared,
    ),
    persistence_scenario("persistence/write-interruption", Runner::PersistenceWriteInterruption),
    persistence_scenario("persistence/recovery", Runner::PersistenceRecovery),
    persistence_scenario("persistence/corruption-detected", Runner::PersistenceCorruption),
    configured("network/transport-dhcp", "network", &[], Fixture::Fresh),
    configured("network/device-bind", "network", &[], Fixture::Fresh),
    configured_with_runner(
        "network/configuration",
        "network",
        &[],
        Fixture::Fresh,
        Runner::NetworkConfiguration,
    ),
    configured("network/unauthorized-operation", "network", &[], Fixture::Fresh),
    configured("network/simultaneous-client-busy", "network", &[], Fixture::Fresh),
    configured("network/icmp-echo", "network", &[], Fixture::Fresh),
    configured("network/udp-round-trip", "network", &[], Fixture::Fresh),
    configured("network/backpressure-cancel", "network", &[], Fixture::Fresh),
    configured("network/packet-loss", "network", &[], Fixture::Fresh),
    configured("network/timeout", "network", &[], Fixture::Fresh),
    configured("network/reset-reconnect", "network", &[], Fixture::Fresh),
    configured("network/tcp-stream", "remote", &[], Fixture::Fresh),
    configured("remote/enrollment-persistence", "remote", &[], Fixture::Persistence),
    configured_with_runner(
        "remote/auth-denied",
        "remote",
        &[],
        Fixture::Fresh,
        Runner::RemoteAuthDenied,
    ),
    configured_with_runner(
        "remote/typed-invoke",
        "remote",
        &[],
        Fixture::Fresh,
        Runner::RemoteTypedInvoke,
    ),
    configured("remote/reconnect-replay", "remote", &[], Fixture::Persistence),
    configured("remote/pending-after-reset", "remote", &[], Fixture::Persistence),
    configured("remote/gateway-restart", "remote", &[], Fixture::Fresh),
    configured("remote/protected-state-corrupt", "remote", &[], Fixture::Persistence),
];

const fn scenario(id: &'static str, suite: &'static str, fixture: Fixture) -> Scenario {
    future(id, suite, fixture)
}

const fn configured(
    id: &'static str,
    suite: &'static str,
    setup: &'static [&'static str],
    fixture: Fixture,
) -> Scenario {
    configured_with_runner(id, suite, setup, fixture, Runner::Default)
}

const fn configured_with_runner(
    id: &'static str,
    suite: &'static str,
    setup: &'static [&'static str],
    fixture: Fixture,
    runner: Runner,
) -> Scenario {
    Scenario { id, suite, timeout: 20, implemented: true, setup, fixture, runner }
}

const fn future(id: &'static str, suite: &'static str, fixture: Fixture) -> Scenario {
    Scenario {
        id,
        suite,
        timeout: 20,
        implemented: false,
        setup: &[],
        fixture,
        runner: Runner::Default,
    }
}

const fn persistence_scenario(id: &'static str, runner: Runner) -> Scenario {
    Scenario {
        id,
        suite: "persistence",
        timeout: 60,
        implemented: true,
        setup: &[],
        fixture: Fixture::Persistence,
        runner,
    }
}
