[package]
name = "logos-test"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
logos-abi = { path = "../logos-abi" }
logos-store = { path = "../logos-store" }
logos-terminal = { path = "../logos-terminal" }
logos-remote = { path = "../logos-remote" }
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
