[package]
name = "logos-service-images"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[features]
qemu-proof = []
package-proof = []
storage-proof = []
fetch-proof = []
user-kdf = ["logos-user/password-kdf"]

[dependencies]
logos-abi = { path = "../../abi" }
logos-flow = { path = "../flow" }
logos-device = { path = "../device" }
logos-display = { path = "../display" }
logos-input = { path = "../input" }
logos-session = { path = "../session" }
logos-storage = { path = "../../storage" }
logos-storage-service = { path = "../storage" }
logos-user = { path = "../user", default-features = false }
logos-terminal = { path = "../terminal" }
logos-network = { path = "../../network" }
logos-fetch = { path = "../fetch" }

[[bin]]
name = "logos-input"
path = "src/input.rs"
test = false
bench = false

[[bin]]
name = "logos-display"
path = "src/display.rs"
test = false
bench = false

[[bin]]
name = "logos-terminal"
path = "src/terminal.rs"
test = false
bench = false

[[bin]]
name = "logos-session"
path = "src/session.rs"
test = false
bench = false

[[bin]]
name = "logos-flow"
path = "src/flow.rs"
test = false
bench = false

[[bin]]
name = "logos-storage"
path = "src/storage.rs"
test = false
bench = false

[[bin]]
name = "logos-network"
path = "src/network.rs"
test = false
bench = false

[[bin]]
name = "logos-fetch"
path = "src/fetch.rs"
test = false
bench = false

[[bin]]
name = "logos-device"
path = "src/device.rs"
test = false
bench = false

[[bin]]
name = "logos-user"
path = "src/user.rs"
test = false
bench = false
