[package]
name = "logos-network"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[dependencies]
logos-abi = { path = "../abi" }
smoltcp = { version = "=0.12.0", default-features = false, features = [
    "medium-ethernet",
    "proto-ipv4",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "socket-dhcpv4",
] }
