[package]
name = "logos-user"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[lib]
test = true
bench = false

[features]
default = ["password-kdf"]
password-kdf = ["argon2/alloc"]

[dependencies]
argon2 = { version = "0.5.3", default-features = false }
logos-abi = { path = "../../abi" }
