[package]
name = "logos-network-service"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
logos-abi = { path = "../logos-abi" }
logos-net = { path = "../logos-net" }
logos-service-rt = { path = "../logos-service-rt" }

[[bin]]
name = "logos-network-service"
path = "src/main.rs"
