[package]
name = "logos-input"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[lib]
test = true
bench = false

[dependencies]
logos-abi = { path = "../../abi" }

[dev-dependencies]
logos-flow = { path = "../flow" }
logos-session = { path = "../session" }
logos-terminal = { path = "../terminal" }
