//! Text measurement for the offline Inter ASCII atlases (ADR-0088).
//!
//! Advance widths are the single source of truth shared by the UI scene
//! builder (which needs them to size and center labels) and Display (which
//! needs them to advance the raster cursor). The raster coverage bitmaps
//! stay in `logos-display`, the sole framebuffer writer; only the per-glyph
//! pixel widths live here, generated by `scripts/gen_inter_atlas.py` from
//! `third_party/Inter-Regular.ttf` (Inter v4.1, SIL OFL 1.1).
//!
//! ASCII only (0x20..=0x7e); any other scalar measures as the replacement
//! glyph's advance, matching the raster fallback.

include!("inter_advances.rs");

pub const INTER_ASCII_FIRST: u32 = 0x20;
pub const INTER_ASCII_LAST: u32 = 0x7e;
/// Printable ASCII glyphs, not counting the trailing replacement glyph.
pub const INTER_GLYPH_COUNT: usize = (INTER_ASCII_LAST - INTER_ASCII_FIRST + 1) as usize;

/// Fixed raster cell (width, height) in pixels for the Inter body atlas (14 px).
pub const INTER_BODY_CELL: (usize, usize) = (16, 18);
/// Fixed raster cell (width, height) in pixels for the Inter title atlas (20 px).
pub const INTER_TITLE_CELL: (usize, usize) = (22, 25);

const _: () = assert!(INTER_BODY_ADVANCES.len() == INTER_GLYPH_COUNT + 1);
const _: () = assert!(INTER_TITLE_ADVANCES.len() == INTER_GLYPH_COUNT + 1);

/// Which bundled proportional style a `GlyphRun` command selects. Terminal
/// and the retained `TextGrid` node never use this: they keep the fixed 8x16
/// JetBrains Mono atlas addressed directly by `logos-display`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InterStyle {
    Body,
    Title,
}

impl InterStyle {
    pub const fn cell(self) -> (usize, usize) {
        match self {
            InterStyle::Body => INTER_BODY_CELL,
            InterStyle::Title => INTER_TITLE_CELL,
        }
    }

    const fn advances(self) -> &'static [u8; INTER_GLYPH_COUNT + 1] {
        match self {
            InterStyle::Body => &INTER_BODY_ADVANCES,
            InterStyle::Title => &INTER_TITLE_ADVANCES,
        }
    }
}

/// Index into an advance/coverage table for `scalar`, folding anything
/// outside printable ASCII onto the trailing replacement glyph.
pub const fn inter_glyph_index(scalar: u32) -> usize {
    if scalar >= INTER_ASCII_FIRST && scalar <= INTER_ASCII_LAST {
        (scalar - INTER_ASCII_FIRST) as usize
    } else {
        INTER_GLYPH_COUNT
    }
}

/// Pixel advance width of one glyph in the given style.
pub const fn inter_glyph_advance(style: InterStyle, scalar: u32) -> u8 {
    style.advances()[inter_glyph_index(scalar)]
}

/// Total pixel width of `text` (ASCII/Latin-1 byte string) set in `style`,
/// with no kerning or shaping: the sum of per-glyph advances. This is the
/// measurement layout uses to size and center labels before Display ever
/// rasterizes them.
pub fn inter_text_width(style: InterStyle, text: &[u8]) -> u32 {
    text.iter().map(|&byte| u32::from(inter_glyph_advance(style, u32::from(byte)))).sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn measured_width_matches_advance_sum() {
        let text = b"Settings";
        let mut expected = 0u32;
        for &byte in text {
            expected += u32::from(inter_glyph_advance(InterStyle::Body, u32::from(byte)));
        }
        assert_eq!(inter_text_width(InterStyle::Body, text), expected);
        assert_eq!(inter_text_width(InterStyle::Title, text), {
            let mut expected = 0u32;
            for &byte in text {
                expected += u32::from(inter_glyph_advance(InterStyle::Title, u32::from(byte)));
            }
            expected
        });
    }

    #[test]
    fn empty_text_measures_zero() {
        assert_eq!(inter_text_width(InterStyle::Body, b""), 0);
    }

    #[test]
    fn unsupported_scalar_falls_back_to_replacement_advance() {
        let replacement = InterStyle::Body.advances()[INTER_GLYPH_COUNT];
        assert_eq!(inter_glyph_advance(InterStyle::Body, 0x1f600), replacement);
        assert_eq!(inter_glyph_advance(InterStyle::Body, 0x00), replacement);
    }

    #[test]
    fn every_advance_fits_its_cell_width() {
        let (body_w, _) = INTER_BODY_CELL;
        let (title_w, _) = INTER_TITLE_CELL;
        assert!(INTER_BODY_ADVANCES.iter().all(|&advance| (advance as usize) <= body_w));
        assert!(INTER_TITLE_ADVANCES.iter().all(|&advance| (advance as usize) <= title_w));
    }
}
