[package]
name = "logosctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
logos-remote = { path = "../logos-remote" }
noise-protocol = { version = "0.2", default-features = false, features = ["use_std"] }
rand_core = { version = "0.6", features = ["getrandom"], default-features = false }
x25519-dalek = { version = "2.0", features = ["static_secrets", "getrandom"] }
