#!/usr/bin/env python3
"""Generate the offline Inter ASCII coverage atlases used by services/display.

Reads third_party/Inter-Regular.ttf (Inter v4.1, SIL OFL 1.1 -- see
third_party/Inter-OFL.txt) and rasterizes the printable ASCII range
(0x20..=0x7e) plus one replacement glyph into fixed-size 8-bit coverage grids,
at 14 px (body) and 20 px (title). Output mirrors the existing JetBrains Mono
atlas convention (services/display/src/jetbrains_mono_8x16.bin): row-major
8-bit coverage bytes, one fixed-size cell per glyph, glyphs ordered by
codepoint with the replacement glyph last.

Each output file is:
  [advances: (glyph_count) u8 bytes, one pixel width per glyph]
  [coverage: (glyph_count) * height * width u8 bytes]

Regenerate with: python scripts/gen_inter_atlas.py
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONT_PATH = ROOT / "third_party" / "Inter-Regular.ttf"
ASCII_FIRST = 0x20
ASCII_LAST = 0x7E
GLYPH_COUNT = ASCII_LAST - ASCII_FIRST + 1  # + 1 replacement glyph appended

# (name, pixel size, cell width, cell height, baseline/ascent row)
STYLES = [
    ("body", 14, 16, 18, 14),
    ("title", 20, 22, 25, 20),
]

ADVANCES_RS_PATH = ROOT / "abi" / "src" / "inter_advances.rs"


def replacement_glyph(width: int, height: int) -> bytes:
    """A deterministic hollow-box tofu glyph, independent of font coverage."""
    rows = bytearray(width * height)
    for y in range(height):
        for x in range(width):
            on_border = x in (1, width - 2) or y in (1, height - 2)
            if 1 <= x <= width - 2 and 1 <= y <= height - 2 and on_border:
                rows[y * width + x] = 255
    return bytes(rows)


def render_glyph(font: ImageFont.FreeTypeFont, ch: str, width: int, height: int, baseline: int) -> tuple[bytes, int]:
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((0, baseline), ch, font=font, fill=255, anchor="ls")
    advance = round(font.getlength(ch))
    advance = max(1, min(advance, width, 255))
    return image.tobytes(), advance


def generate(name: str, size: int, width: int, height: int, baseline: int) -> bytes:
    font = ImageFont.truetype(str(FONT_PATH), size)
    advances = bytearray()
    coverage = bytearray()
    for codepoint in range(ASCII_FIRST, ASCII_LAST + 1):
        glyph_bytes, advance = render_glyph(font, chr(codepoint), width, height, baseline)
        advances.append(advance)
        coverage.extend(glyph_bytes)
    advances.append(width)  # replacement glyph advance: fill the cell
    coverage.extend(replacement_glyph(width, height))

    out_path = ROOT / "services" / "display" / "src" / f"inter_{name}_{width}x{height}.bin"
    out_path.write_bytes(bytes(coverage))
    total_glyphs = GLYPH_COUNT + 1
    assert len(advances) == total_glyphs
    assert len(coverage) == total_glyphs * width * height
    print(f"wrote {out_path} ({len(coverage)} bytes, {total_glyphs} glyphs)")
    return bytes(advances)


def write_advances_rs(advances_by_style: dict[str, bytes]) -> None:
    lines = [
        "// Generated by scripts/gen_inter_atlas.py from third_party/Inter-Regular.ttf",
        "// (Inter v4.1, SIL OFL 1.1 -- see third_party/Inter-OFL.txt). Do not edit by hand.",
        "",
    ]
    for name, advances in advances_by_style.items():
        values = ", ".join(str(b) for b in advances)
        lines.append(
            f"pub const INTER_{name.upper()}_ADVANCES: [u8; {len(advances)}] = [{values}];"
        )
    ADVANCES_RS_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {ADVANCES_RS_PATH} ({len(advances_by_style)} tables)")


def main() -> None:
    if not FONT_PATH.exists():
        raise SystemExit(
            f"missing {FONT_PATH}; download Inter-Regular.ttf from "
            "https://github.com/rsms/inter/releases (v4.1) into third_party/"
        )
    advances_by_style = {}
    for name, size, width, height, baseline in STYLES:
        advances_by_style[name] = generate(name, size, width, height, baseline)
    write_advances_rs(advances_by_style)


if __name__ == "__main__":
    main()
